name: Test go-guru
on: [push, pull_request]
jobs:
  build:
    name: Run go-guru
    runs-on: ubuntu-latest
    steps:
    - uses: jferrl/go-guru@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}